import Image from "next/image";

const intelligenceCards = [
  {
    id: 1,
    image: "/franchise/site-selection.png",
    title: "Site Selection Intelligence",
    description: (
      <>
        Foot traffic, demographic fit, delivery density, competitive intensity —
        <br />
        recommended locations generated by data, not guesswork.
      </>
    ),
  },
  {
    id: 2,
    image: "/franchise/demand-forecasting.png",
    title: "Demand Forecasting",
    description: (
      <>
        Real-time demand visibility and SKU mix optimization — operators see
        <br />
        what is likely to sell before they stock it.
      </>
    ),
  },
  {
    id: 3,
    image: "/franchise/operator-scoring.png",
    title: "Operator Scoring",
    description: (
      <>
        Continuous performance scoring against network benchmarks. Early
        <br />
        signals for both opportunity and risk.
      </>
    ),
  },
];

export default function FranchiseIntelligence() {
  return (
    <section className="w-full bg-[#FFFFFF] py-[72px]">
<div className="mx-auto flex max-w-[1440px] flex-col gap-10 px-5 lg:flex-row lg:items-start lg:gap-[60px] lg:px-[92px]">
      {/* Left Content */}
        <div className="w-[680px] max-w-full">
          {/* Heading */}
          <h2 className="font-[Poppins] text-4xl font-semibold leading-tight lg:leading-[57px] text-[#1A0E04]">
            INTELLIGENCE BUILT INTO
            <br />
            EVERY DECISION.
          </h2>

          {/* Description */}
          <p className="mt-4 font-[Poppins] text-base font-normal leading-7 text-[#8C8070]">
            AI makes the network more predictable, more efficient, and more
           
            defensible. It removes weak assumptions from expansion decisions and
            
            supports performance confidence from day one.
          </p>

          {/* Feature Cards */}
          <div className="mt-6 space-y-6" >
            {intelligenceCards.map((card) => (
              <div
                key={card.id}
                className="flex items-start rounded-xl border border-[#EAE4D9] bg-white px-[21px] py-[21px] shadow-[0px_2px_8px_rgba(26,14,4,0.06)]"
              >
                {/* Icon */}
                <div className="flex h-11 w-11 items-center justify-center rounded-[10px] bg-[#FEF3DC]">
                  <Image
                    src={card.image}
                    alt={card.title}
                    width={22}
                    height={22}
                    className="object-contain"
                  />
                </div>

                {/* Text */}
                <div className="ml-5">
                  <h3 className="font-[Poppins] text-base font-bold text-[#1A0E04]">
                    {card.title}
                  </h3>

                  <div className="mt-2 font-[Poppins] text-xs font-normal leading-5 text-[#8C8070]">
                    {card.description}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* ROI Calculator */}
        <div className="w-[588px] max-w-full rounded-[20px] border border-[#FCDFA0] bg-[#FEF3DC] p-[33px]">
                      <h3 className="font-[Bebas_Neue] text-3xl text-[#1A0E04]">
            ROI Calculator
          </h3>

          <p className="mt-2  font-[Poppins] text-sm text-[#4A3F32]">
            Indicative projections based on format and investment level. Full
            models shared during diligence.
          </p>

          {/* Form */}
          <div className="mt-8 space-y-6">
            {/* Format Type */}
            <div>
              <label className="mb-2 block font-[Poppins] text-xs font-bold uppercase tracking-wide text-[#9A5E00]">
                Format Type
              </label>

              <div className="flex h-11 items-center rounded-xl border border-[#FCDFA0] bg-white px-5">
                <span className="font-[Poppins] text-sm text-[#1A0E04]">
                  Express Kiosk
                </span>
              </div>
            </div>

            {/* Target Market */}
            <div>
              <label className="mb-2 block font-[Poppins] text-xs font-bold uppercase tracking-wide text-[#9A5E00]">
                Target Market
              </label>

              <div className="flex h-11 items-center rounded-xl border border-[#FCDFA0] bg-white px-5">
                <span className="font-[Poppins] text-sm text-[#1A0E04]">
                  United States
                </span>
              </div>
            </div>

            {/* Investment Level */}
            <div>
              <label className="mb-2 block font-[Poppins] text-xs font-bold uppercase tracking-wide text-[#9A5E00]">
                Investment Level
              </label>

              <div className="flex h-11 items-center rounded-xl border border-[#FCDFA0] bg-white px-5">
                <span className="font-[Poppins] text-sm text-[#1A0E04]">
                  Entry Operator (1 unit)
                </span>
              </div>
            </div>

            {/* Operating Experience */}
            <div>
              <label className="mb-2 block font-[Poppins] text-xs font-bold uppercase tracking-wide text-[#9A5E00]">
                Operating Experience
              </label>

              <div className="flex h-11 items-center rounded-xl border border-[#FCDFA0] bg-white px-5">
                <span className="font-[Poppins] text-sm text-[#1A0E04]">
                  First-time operator
                </span>
              </div>
            </div>
          </div>

          {/* Button */}
          <button className="mt-8 flex h-12 w-full items-center justify-center rounded-xl bg-[#E8920A] font-[Poppins] text-base font-bold text-white shadow-[0px_4px_12px_rgba(232,146,10,0.30)] transition hover:opacity-90">
            Generate Indicative ROI →
          </button>
        </div>
      </div>
    </section>
  );
}